server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # AUTH-SERVICE routes - NO JWT CHECK
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**,/authenticate

            # USER-SERVICE routes - JWT PROTECTED (NO StripPrefix)
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**,/api/v1/user-info/**,/api/v1/educations/**,/api/v1/achievements/**,/api/v1/job-history/**,/api/v1/register/user
              # NO StripPrefix - User Service already has /api/v1

            # COMPANY-SERVICE routes - JWT PROTECTED (NO StripPrefix)
            - id: COMPANY-SERVICE
              uri: lb://COMPANY-SERVICE
              predicates:
                - Path=/api/v1/companies/**,/api/v1/company-information/**,/api/v1/company-addresses/**,/api/v1/register/company
              # NO StripPrefix

            # JOB-SERVICE routes - MIXED (NO StripPrefix)
            - id: JOB-SERVICE
              uri: lb://JOB-SERVICE
              predicates:
                - Path=/api/v1/jobs/**,/api/v1/applications/**,/api/v1/categories/**
              # NO StripPrefix

            # NOTIFICATION-SERVICE routes - JWT PROTECTED (NO StripPrefix)
            - id: NOTIFICATION-SERVICE
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notifications/**,/api/v1/emails/**,/api/v1/alerts/**
              # NO StripPrefix

# JWT Configuration - YEH ADD KARO
jwt:
  secret: "mysecretkey123456789012345678901234"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.ahad.gateway.filter: DEBUG

# App info
info:
  app:
    name: API-GATEWAY
    version: 1.0.0

