server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
            - Path=/api/v1/job-history/**
            - Path=/api/v1/user-info/**
            - Path=/api/v1/achievements/**
            - Path=/api/v1/addresses/**
            - Path=/api/v1/educations/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /$\{remaining}

        - id: COMPANY-SERVICE
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/v1/companies/**
            - Path=/api/v1/company-addresses/**
            - Path=/api/v1/company-information/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /$\{remaining}

        - id: JOB-SERVICE
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/v1/jobs/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /$\{remaining}

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /$\{remaining}

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: API-GATEWAY
    version: 1.0.0
    description: Development config - all actuator endpoints exposed
