server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # ✅ AUTH SERVICE - Public
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /${remaining}

        # ✅ USER SERVICE - Mixed (Some public, some secure)
        - id: USER-SERVICE-PUBLIC
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/register/user/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /${remaining}
          # ⚡ No AuthenticationFilter - Public registration

        - id: USER-SERVICE-SECURE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**, /api/v1/job-history/**, /api/v1/user-info/**, /api/v1/achievements/**, /api/v1/addresses/**, /api/v1/educations/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /${remaining}
            - name: JwtAuthenticationFilter   # ✅ Custom filter name

        # ✅ COMPANY SERVICE - Mixed
        - id: COMPANY-SERVICE-PUBLIC
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/v1/register/company/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /${remaining}
          # ⚡ No AuthenticationFilter - Public registration

        - id: COMPANY-SERVICE-SECURE
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/v1/companies/**, /api/v1/company-addresses/**, /api/v1/company-information/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /${remaining}
            - name: JwtAuthenticationFilter

        # ✅ JOB SERVICE - Secure
        - id: JOB-SERVICE
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/v1/jobs/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /${remaining}
            - name: JwtAuthenticationFilter

        # ✅ NOTIFICATION SERVICE - Secure
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /${remaining}
            - name: JwtAuthenticationFilter

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: API-GATEWAY
    version: 1.0.0
    description: Development config - all actuator endpoints exposed
