server:
  port: 8085

spring:
  application:
    name: AUTH-SERVICE
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

# JWT Configuration
jwt:
  secret: "mysecretkey123456789012345678901234"  # Minimum 32 characters for HS256
  expiration: 3600   # 1 hour in seconds

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Logging
logging:
  level:
    root: INFO
    com.ahad: DEBUG
    org.springframework.cloud.openfeign: DEBUG
