server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ahad_job_portal?useSSL=false&serverTimezone=UTC
    username: root
    password: Harun@786
    spring:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      idle-timeout: 300000
      keepalive-time: 300000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, env, beans, threaddump, heapdump
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      companyServiceCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
